const verbs = [
   'Deber',//
   'Cantar',//
   'Amar',//
   'Cenar',//
   'Desayunar',
   'Sumar',//
   'Pintar',
   'Molestar',
   'Ayudar',
   'Tomar',
   'Aprender',//
   'Cantar',
   "Buscar",
   'Dibujar',
   'Montar',
   'Luchar',
   'Reconizar',
   'Abrir',//
   'Cerrar',
   'Hablar',
   'Leer',//
   "Pescar",
   "Colocar",
   "Manejar",
   "Caminar",//
   "Cantar",//
   "Montar",
   "Comprender",//
   "Comer",//
   "Beber",//
   "Traer",
   "Ofrecer",
   "Romper",//
   "Vender",
   "Compartir",//
   "Consistir",///
   "Decidir",//
   "Vivir",//
   "Ocurrir",//
   "Suceder",
   "Vivir",//
]